version: "3"
 
services:
  mysql:
    image: mysql:5.7.11
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
  web:
    build: .
    command: /myapp/script/start.sh
    volumes:
      - .:/myapp
    ports:
      - 3000:3000
    depends_on:
      - mysql
