# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1844f813d628af2d941c82af59b41392801a08de38e1488b23c80752375bcb478bd324acdd2d66f6409effab1d7fa203edb72481b1190061a1c971a610473736

test:
  secret_key_base: a22392c17c42c4d934d9c30f9ea3e1170a1593da3f45ccc0c375db7618524da06a560660df12cacbcae85785f9c8297415fe3cdc44015c25c1d48a74a87005ba

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
